version: "3.9"

networks:
  apartment_network:

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./temp/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=banana
    networks:
      - apartment_network
  apartmentservice:
    build: .
    image: apartment-api
    restart: always
    depends_on:
      - mysql
    ports:
      - 3011:3011
    volumes:
      - ./temp/public:/public
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=apartment
      - DB_USER=root
      - DB_PASS=banana
      - SECRET=abc
    networks:
      - apartment_network
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    container_name: myadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_USER: root
      PMA_PASSWORD: banana
      PMA_HOST: mysql
      PMA_PORTS: 3306
    networks:
      - apartment_network

